/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibC2Loader */

#ifndef _Included_LibC2Loader
#define _Included_LibC2Loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibC2Loader
 * Method:    inject
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_LibC2Loader_inject
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
